[project]
name = "condenser2"
version = "0.1.0"
description = "Condenser2"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "faker==38.2.0",
    "mysql-connector-python==9.5.0",
    "psycopg[binary]==3.2.13",
    "toposort==1.10",
]


[project.scripts]
subset = "condenser2.direct_subset:main"

[dependency-groups]
dev = [
    "pytest>=8",
    "ruff==0.15.11",
]

[tool.ruff.lint]
extend-select = ["I"]

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"
